import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/About.module.css'

const About = ()=> {
  return (
    <div className={style.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className={style.aboutContainer}>
        <span className={style.aboutSubheading}>Lorem, ipsum dolor sit amet consectetur</span>
        <h1 className={style.heading}>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius velit sint fugiat, ipsum inventore tenetur esse alias voluptate pariatur eos! Consequuntur illo excepturi autem corporis!</p>
        <div>
        <Image
        className={style.myImage}
          src=""
          layout="fill"
          objectFit="cover"
          alt=""
        />
        <span>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim est alias repellat eos. Voluptatum totam dolore iste voluptate, iusto est officiis illum saepe.</span>
        </div>

       </div>

</div>
  )
}
export default About
